/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projket;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author abdurrezzak
 */
public class anEntry extends javax.swing.JFrame {

    User curUser = new User();
    String curusername="";
    String curEnt = "";
    boolean showImage = false;
    
    public anEntry() throws FileNotFoundException, IOException, ClassNotFoundException {
        initComponents();
        
        surfacePanel.setBackground(new Color(19,19,19,100));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        pic.setVisible(false);
        cl.setVisible(false);
        String line = null; 
        FileReader fileReader = new FileReader("sessions/usernames.txt");
        try (BufferedReader bufferedReader = new BufferedReader(fileReader)) {
            while((line = bufferedReader.readLine()) != null) {
                curusername = line;
            }
        } 
        
        /*
            this part gets the info about the current user
        */
        FileInputStream fis = new FileInputStream("users/"+curusername+".ser");
        ObjectInputStream ois = new ObjectInputStream(fis);
        curUser = (User) ois.readObject();
        
        line = null; 
        FileReader fileReader2 = new FileReader("sessions/curEntryTit.txt");
        try (BufferedReader bufferedReader = new BufferedReader(fileReader2)) {
            while((line = bufferedReader.readLine()) != null) {
                curEnt = line;
            }
        } 
        
        
        //JOptionPane.showMessageDialog(new JFrame(), curEnt);
        Entry e = new Entry();
        e.setTitle(curEnt);
        System.out.println(curUser.getSpecificEntry(e).getText());
        e = curUser.getSpecificEntry(e);
        tit.setText(e.getTitle());
        content.setText(e.getText());
        content.setBackground(new Color(19,19,19,0));
        imagesList.setBackground(new Color(19,19,19,70));
        
        DefaultListModel dm = new DefaultListModel();
        
        for(int i=0;i<e.getMedia().size();i++)
        {
            dm.addElement(new ImageIcon(new ImageIcon(e.getMedia().get(i).img).getImage().getScaledInstance(112, 112, Image.SCALE_SMOOTH)));
        }
        
        imagesList.setModel(dm);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic = new javax.swing.JLabel();
        cl = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tit = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        imagesList = new javax.swing.JList<>();
        surfacePanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(254, 123, 241)));
        pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picMouseClicked(evt);
            }
        });
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 600, 530));

        cl.setText("Close");
        getContentPane().add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, -1));

        tit.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        tit.setForeground(new java.awt.Color(254, 214, 237));
        getContentPane().add(tit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 590, 50));

        content.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        content.setForeground(new java.awt.Color(255, 200, 248));
        jScrollPane2.setViewportView(content);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 110, 480, 390));

        imagesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        imagesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                imagesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(imagesList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 130, 390));
        getContentPane().add(surfacePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 590));

        mainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/bcghome.jpg"))); // NOI18N
        getContentPane().add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 683, 587));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        this.dispose();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imagesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_imagesListValueChanged
        
        if(!showImage)
        {
            
            showImage =  true;
            
        }
        
        int i = imagesList.getSelectedIndex();
        Entry e = new Entry();
        e.setTitle(curEnt);
        e = curUser.getSpecificEntry(e);

       // JOptionPane.showMessageDialog(new JFrame(), e.getMedia().get(i).img);


        pic.setIcon(new ImageIcon(new ImageIcon(e.getMedia().get(i).img).getImage().getScaledInstance(600, 530, Image.SCALE_SMOOTH)));
        
        pic.setVisible(true);
        cl.setVisible(true);
        
        
    }//GEN-LAST:event_imagesListValueChanged

    private void picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picMouseClicked
        // TODO add your handling code here:
        pic.setVisible(false);
        cl.setVisible(false);
    }//GEN-LAST:event_picMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new anEntry().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(anEntry.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(anEntry.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cl;
    private javax.swing.JTextPane content;
    private javax.swing.JList<String> imagesList;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel pic;
    private javax.swing.JPanel surfacePanel;
    private javax.swing.JLabel tit;
    // End of variables declaration//GEN-END:variables
}
