/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projket;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author abdurrezzak
 */
public class Notes extends javax.swing.JFrame {

    User curUser = new User();
    String curusername="";
    Note newNote = new Note();
        
    Note n = new Note(); //for deleting and display
    
    public Notes() throws FileNotFoundException, IOException, ClassNotFoundException {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        jPanel1.setBackground(new Color(82,3,68,0));
        oldNotesList.setBackground(new Color(0,0,0));
        addingNotebcg.setIcon(new ImageIcon(new ImageIcon("/home/abdurrezzak/NetBeansProjects/Projket/src/projket/postit.jpg").getImage().getScaledInstance(670, 530, Image.SCALE_SMOOTH)));
        aNote.setVisible(false);
        aNote.setBackground(new Color(0,0,0,0));
        aNoteContent.setBackground(new Color(0,0,0,0));
        bcgANote.setIcon(new ImageIcon(new ImageIcon("/home/abdurrezzak/NetBeansProjects/Projket/src/projket/postit.jpg").getImage().getScaledInstance(670, 530, Image.SCALE_SMOOTH)));
        String line = null; 
        FileReader fileReader = new FileReader("sessions/usernames.txt");
        try (BufferedReader bufferedReader = new BufferedReader(fileReader)) {
            while((line = bufferedReader.readLine()) != null) {
                curusername = line;
            }
        } 
        
        
        FileInputStream fis = new FileInputStream("users/"+curusername+".ser");
        ObjectInputStream ois = new ObjectInputStream(fis);
        curUser = (User) ois.readObject();
        
        //getting current info
        propicLabel.setIcon(new ImageIcon(new ImageIcon(curUser.getProfilePicture()).getImage().getScaledInstance(200, 150, Image.SCALE_SMOOTH)));
        usernameLabel.setText("Welcome "+curUser.getUsername() + "!");
        
        
        propicLabel.setToolTipText("Click here to change your profile picture!");
        
        DefaultListModel dm = new DefaultListModel();
        
        for(int i=0;i<curUser.getNotes().size();i++)
        {
            dm.addElement(curUser.getNotes().get(i).getTitle());
        }
        
        oldNotesList.setModel(dm);
        
        
        addingNote.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aNote = new javax.swing.JPanel();
        aNoteTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        aNoteContent = new javax.swing.JTextArea();
        aNotePic = new javax.swing.JLabel();
        deleteNoteBut = new javax.swing.JButton();
        bcgANote = new javax.swing.JLabel();
        addingNote = new javax.swing.JPanel();
        createdNote = new javax.swing.JButton();
        newNoteTitle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        newNoteContent = new javax.swing.JTextArea();
        newNotePic = new javax.swing.JLabel();
        newNoteAddImageBut = new javax.swing.JButton();
        addingNotebcg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oldNotesList = new javax.swing.JList<>();
        addNoteBut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nyxBut = new javax.swing.JButton();
        newEntryBut = new javax.swing.JButton();
        yourDaysBut = new javax.swing.JButton();
        propicLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        notesBut = new javax.swing.JButton();
        oldEntriesBut = new javax.swing.JButton();
        albumsBut = new javax.swing.JButton();
        oldTalksBut = new javax.swing.JButton();
        exitBut = new javax.swing.JLabel();
        settingsBut = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bcghomelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 670));
        setMinimumSize(new java.awt.Dimension(1280, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aNoteMouseClicked(evt);
            }
        });
        aNote.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aNoteTitle.setFont(new java.awt.Font("Ubuntu", 2, 28)); // NOI18N
        aNoteTitle.setForeground(new java.awt.Color(181, 7, 202));
        aNote.add(aNoteTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 530, 80));

        aNoteContent.setColumns(20);
        aNoteContent.setRows(5);
        aNoteContent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(219, 32, 254), new java.awt.Color(219, 32, 254)));
        jScrollPane3.setViewportView(aNoteContent);

        aNote.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 310, 270));

        aNotePic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(219, 32, 254), new java.awt.Color(219, 32, 254)));
        aNote.add(aNotePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 270, 270));

        deleteNoteBut.setText("Delete Note");
        deleteNoteBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteNoteButMouseClicked(evt);
            }
        });
        aNote.add(deleteNoteBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));
        aNote.add(bcgANote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 530));

        getContentPane().add(aNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 690, 530));

        addingNote.setBackground(new java.awt.Color(1, 1, 1));
        addingNote.setForeground(new java.awt.Color(254, 180, 231));
        addingNote.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createdNote.setBackground(new java.awt.Color(82, 3, 69));
        createdNote.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        createdNote.setForeground(new java.awt.Color(253, 186, 224));
        createdNote.setText("OK");
        createdNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createdNoteMouseClicked(evt);
            }
        });
        addingNote.add(createdNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 90, -1));

        newNoteTitle.setBackground(new java.awt.Color(82, 3, 69));
        newNoteTitle.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        newNoteTitle.setForeground(new java.awt.Color(253, 186, 224));
        newNoteTitle.setText("Title");
        addingNote.add(newNoteTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 38, 590, 40));

        newNoteContent.setBackground(new java.awt.Color(82, 3, 69));
        newNoteContent.setColumns(15);
        newNoteContent.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        newNoteContent.setForeground(new java.awt.Color(253, 186, 224));
        newNoteContent.setRows(5);
        jScrollPane2.setViewportView(newNoteContent);

        addingNote.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 340, 270));
        addingNote.add(newNotePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 200, 210));

        newNoteAddImageBut.setBackground(new java.awt.Color(82, 3, 69));
        newNoteAddImageBut.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        newNoteAddImageBut.setForeground(new java.awt.Color(253, 186, 224));
        newNoteAddImageBut.setText("Add Image");
        newNoteAddImageBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newNoteAddImageButMouseClicked(evt);
            }
        });
        addingNote.add(newNoteAddImageBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 200, 40));
        addingNote.add(addingNotebcg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 450));

        getContentPane().add(addingNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 690, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/rsz_2logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 240, 100));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 210));
        jLabel1.setText("Notes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 450, 50));

        oldNotesList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oldNotesList.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        oldNotesList.setForeground(new java.awt.Color(254, 254, 254));
        oldNotesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        oldNotesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        oldNotesList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        oldNotesList.setNextFocusableComponent(oldNotesList);
        oldNotesList.setVisibleRowCount(100);
        oldNotesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oldNotesListMousePressed(evt);
            }
        });
        oldNotesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                oldNotesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(oldNotesList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 690, 360));

        addNoteBut.setBackground(new java.awt.Color(212, 50, 177));
        addNoteBut.setText("Add Note");
        addNoteBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNoteButMouseClicked(evt);
            }
        });
        getContentPane().add(addNoteBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 330, 90, 90));

        jPanel1.setBackground(new java.awt.Color(82, 3, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nyxBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        nyxBut.setForeground(new java.awt.Color(1, 1, 1));
        nyxBut.setText("TALK TO NYX");
        nyxBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nyxBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nyxBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        nyxBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nyxButMouseClicked(evt);
            }
        });
        nyxBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyxButActionPerformed(evt);
            }
        });
        jPanel1.add(nyxBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 260, 40));

        newEntryBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        newEntryBut.setForeground(new java.awt.Color(1, 1, 1));
        newEntryBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/addentry.png"))); // NOI18N
        newEntryBut.setText("New Entry");
        newEntryBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        newEntryBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newEntryBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newEntryBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        newEntryBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newEntryButMouseClicked(evt);
            }
        });
        newEntryBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntryButActionPerformed(evt);
            }
        });
        jPanel1.add(newEntryBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 40));

        yourDaysBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        yourDaysBut.setForeground(new java.awt.Color(1, 1, 1));
        yourDaysBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/yourdays.png"))); // NOI18N
        yourDaysBut.setText("Your Days");
        yourDaysBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        yourDaysBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        yourDaysBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        yourDaysBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        yourDaysBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yourDaysButMouseClicked(evt);
            }
        });
        yourDaysBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourDaysButActionPerformed(evt);
            }
        });
        jPanel1.add(yourDaysBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 40));

        propicLabel.setBackground(new java.awt.Color(221, 128, 35));
        propicLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        propicLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propicLabelMouseClicked(evt);
            }
        });
        jPanel1.add(propicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 150));

        usernameLabel.setFont(new java.awt.Font("Symbola", 2, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 40));

        notesBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        notesBut.setForeground(new java.awt.Color(1, 1, 1));
        notesBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/notes.png"))); // NOI18N
        notesBut.setText("Notes");
        notesBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notesBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        notesBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        notesBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        notesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesButMouseClicked(evt);
            }
        });
        notesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesButActionPerformed(evt);
            }
        });
        jPanel1.add(notesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 40));

        oldEntriesBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        oldEntriesBut.setForeground(new java.awt.Color(1, 1, 1));
        oldEntriesBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/oldentries.png"))); // NOI18N
        oldEntriesBut.setText("Old Entries");
        oldEntriesBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        oldEntriesBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        oldEntriesBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        oldEntriesBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        oldEntriesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldEntriesButMouseClicked(evt);
            }
        });
        oldEntriesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldEntriesButActionPerformed(evt);
            }
        });
        jPanel1.add(oldEntriesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 40));

        albumsBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        albumsBut.setForeground(new java.awt.Color(1, 1, 1));
        albumsBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/albums.png"))); // NOI18N
        albumsBut.setText("Albums");
        albumsBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        albumsBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        albumsBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        albumsBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        albumsBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumsButMouseClicked(evt);
            }
        });
        albumsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumsButActionPerformed(evt);
            }
        });
        jPanel1.add(albumsBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 120, 40));

        oldTalksBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        oldTalksBut.setForeground(new java.awt.Color(1, 1, 1));
        oldTalksBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/oldtalks.png"))); // NOI18N
        oldTalksBut.setText("Old Talks");
        oldTalksBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        oldTalksBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        oldTalksBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        oldTalksBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        oldTalksBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldTalksButMouseClicked(evt);
            }
        });
        oldTalksBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldTalksButActionPerformed(evt);
            }
        });
        jPanel1.add(oldTalksBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 40));

        exitBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/exitt.png"))); // NOI18N
        exitBut.setText("jLabel3");
        exitBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButMouseClicked(evt);
            }
        });
        jPanel1.add(exitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 50, 50));

        settingsBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/settings.png"))); // NOI18N
        settingsBut.setText("jLabel3");
        settingsBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButMouseClicked(evt);
            }
        });
        jPanel1.add(settingsBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 290, 520));

        jSeparator1.setBackground(new java.awt.Color(203, 218, 64));
        jSeparator1.setForeground(new java.awt.Color(164, 238, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 470));

        bcghomelabel.setBackground(new java.awt.Color(82, 3, 68));
        bcghomelabel.setForeground(new java.awt.Color(254, 254, 254));
        bcghomelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/bcghome.jpg"))); // NOI18N
        bcghomelabel.setText("ASDASADASDASDASDSA");
        bcghomelabel.setOpaque(true);
        getContentPane().add(bcghomelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nyxButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyxButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyxButActionPerformed

    private void newEntryButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntryButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEntryButActionPerformed

    private void yourDaysButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourDaysButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yourDaysButActionPerformed

    private void propicLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propicLabelMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        
        propicLabel.setIcon(new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(200, 150, Image.SCALE_SMOOTH)));
        //ImageIcon icon=new ImageIcon(filename);
        //jLabel3.setIcon(icon);
        
    }//GEN-LAST:event_propicLabelMouseClicked

    private void notesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notesButActionPerformed

    private void oldEntriesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldEntriesButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldEntriesButActionPerformed

    private void albumsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumsButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumsButActionPerformed

    private void oldTalksButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldTalksButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldTalksButActionPerformed

    private void exitButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_exitButMouseClicked

    private void settingsButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButMouseClicked
        this.setVisible(false);
        try {
            new Settings().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_settingsButMouseClicked

    private void newEntryButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEntryButMouseClicked
        
        this.setVisible(false);
        try {
            new NewEntry().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newEntryButMouseClicked

    private void notesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesButMouseClicked
        this.setVisible(false);
        try {
            new Notes().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_notesButMouseClicked

    private void yourDaysButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yourDaysButMouseClicked
        this.setVisible(false);
        try {
            new YourDays().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yourDaysButMouseClicked

    private void oldEntriesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldEntriesButMouseClicked
        this.setVisible(false);
        try {
            new OldEntries().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_oldEntriesButMouseClicked

    private void oldTalksButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldTalksButMouseClicked
        this.setVisible(false);
        try {
            new OldTalks().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_oldTalksButMouseClicked

    private void albumsButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumsButMouseClicked
        this.setVisible(false);
        try {
            new Albums().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_albumsButMouseClicked

    private void nyxButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nyxButMouseClicked
        this.setVisible(false);
        try {
            new Nyx().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nyxButMouseClicked

    private void addNoteButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNoteButMouseClicked
        
        addingNote.setVisible(true);
        
    }//GEN-LAST:event_addNoteButMouseClicked

    private void createdNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createdNoteMouseClicked
        
        
        newNote.setTitle(newNoteTitle.getText());
        newNote.setContent(newNoteContent.getText());
        if(newNote.getPicture() == null)
            newNote.changePicture(new Photo());
         
        curUser.addNote(newNote);
        
        FileOutputStream fout = null;
        File ff = new File("users/"+curUser.getUsername()+".ser");
        ff.delete();
        try {
            fout = new FileOutputStream("users/"+curUser.getUsername()+".ser");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectOutputStream oos = null;
        try {
            oos = new ObjectOutputStream(fout);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            oos.writeObject(curUser);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        addingNote.setVisible(false);
        this.dispose();
        try {
            new Notes().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        newNote = new Note();
        
    }//GEN-LAST:event_createdNoteMouseClicked

    private void newNoteAddImageButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newNoteAddImageButMouseClicked
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        
        newNotePic.setIcon(new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(200, 150, Image.SCALE_SMOOTH)));
        
        Photo p = new Photo();
        p.changeImage(filename);
        newNote.changePicture(p);
        
    }//GEN-LAST:event_newNoteAddImageButMouseClicked

    private void oldNotesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_oldNotesListValueChanged
        
        try{
            int i = oldNotesList.getSelectedIndex();
            
            
            //JOptionPane.showMessageDialog(new JFrame(), "You seem to have forgotten your password, please try again.");

            
            n.setTitle(oldNotesList.getSelectedValue());
            n = curUser.getSpecificNote(n);
            aNoteTitle.setText(n.getTitle());
            aNoteContent.setText(n.getContent());
            aNotePic.setIcon(new ImageIcon(new ImageIcon(n.getPicture().img).getImage().getScaledInstance(270, 270, Image.SCALE_SMOOTH)));

            aNote.setVisible(true);
            
        }catch(NullPointerException e)
        {
            
        }
    }//GEN-LAST:event_oldNotesListValueChanged

    private void aNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aNoteMouseClicked
        
        aNote.setVisible(false);
        
    }//GEN-LAST:event_aNoteMouseClicked

    private void oldNotesListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldNotesListMousePressed
        // TODO add your handling code here:
        oldNotesList.setSelectedIndex(-1);
    }//GEN-LAST:event_oldNotesListMousePressed

    private void deleteNoteButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteNoteButMouseClicked
        
        curUser.deleteNote(n);
        FileOutputStream fout = null;
        File ff = new File("users/"+curUser.getUsername()+".ser");
        ff.delete();
        try {
            fout = new FileOutputStream("users/"+curUser.getUsername()+".ser");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectOutputStream oos = null;
        try {
            oos = new ObjectOutputStream(fout);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            oos.writeObject(curUser);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        aNote.setVisible(false);
        this.dispose();
        try {
            new Notes().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteNoteButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Notes().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aNote;
    private javax.swing.JTextArea aNoteContent;
    private javax.swing.JLabel aNotePic;
    private javax.swing.JLabel aNoteTitle;
    private javax.swing.JButton addNoteBut;
    private javax.swing.JPanel addingNote;
    private javax.swing.JLabel addingNotebcg;
    private javax.swing.JButton albumsBut;
    private javax.swing.JLabel bcgANote;
    private javax.swing.JLabel bcghomelabel;
    private javax.swing.JButton createdNote;
    private javax.swing.JButton deleteNoteBut;
    private javax.swing.JLabel exitBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton newEntryBut;
    private javax.swing.JButton newNoteAddImageBut;
    private javax.swing.JTextArea newNoteContent;
    private javax.swing.JLabel newNotePic;
    private javax.swing.JTextField newNoteTitle;
    private javax.swing.JButton notesBut;
    private javax.swing.JButton nyxBut;
    private javax.swing.JButton oldEntriesBut;
    private javax.swing.JList<String> oldNotesList;
    private javax.swing.JButton oldTalksBut;
    private javax.swing.JLabel propicLabel;
    private javax.swing.JLabel settingsBut;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton yourDaysBut;
    // End of variables declaration//GEN-END:variables
}
