/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projket;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author abdurrezzak
 */
public class Nyx extends javax.swing.JFrame {

    
    String curusername;
    User curUser = new User();
    OldTalk no = new OldTalk();
    String cont = "";
    ChatterBotFactory factory = new ChatterBotFactory();
    ChatterBot bot2 = factory.create(ChatterBotType.PANDORABOTS, "b0dafd24ee35a477");
    ChatterBotSession bot2session = bot2.createSession();
    String usersays = "";
    public Nyx() throws Exception {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        NyxPane.setBackground(new Color(27,181,243,30));
        jScrollPane1.setBackground(new Color(27,181,243,30));
        saying.setBackground(new Color(27,181,243,100));
        Save.setBackground(new Color(27,181,243,10));
        
        
        
        String line = null; 
        FileReader fileReader = new FileReader("sessions/usernames.txt");
        try (BufferedReader bufferedReader = new BufferedReader(fileReader)) {
            while((line = bufferedReader.readLine()) != null) {
                curusername = line;
            }
        } 
        
        FileInputStream fis = new FileInputStream("users/"+curusername+".ser");
        ObjectInputStream ois = new ObjectInputStream(fis);
        curUser = (User) ois.readObject();
        
        
            saying.addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                    cont += curusername+": ";

                    String usersays = saying.getText();
                    cont += usersays;
                    cont += "\n";

                    String s="";
                    try {
                        s = bot2session.think(usersays);
                    } catch (Exception ex) {
                        Logger.getLogger(Nyx.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    cont += "Nyx: " + s +"\r\n";

                    NyxPane.setText(cont);
                    
                    saying.setText("");
                }
            });
            
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        NyxPane = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        saying = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bcghomelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 670));
        setMinimumSize(new java.awt.Dimension(1280, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NyxPane.setColumns(20);
        NyxPane.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        NyxPane.setForeground(new java.awt.Color(0, 37, 255));
        NyxPane.setLineWrap(true);
        NyxPane.setRows(5);
        NyxPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(NyxPane);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 560, 400));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 560, 20));

        saying.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        saying.setForeground(new java.awt.Color(248, 13, 255));
        saying.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(saying, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 440, 40));

        Save.setText("Save");
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/rsz_2logo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, 100));

        jSeparator1.setBackground(new java.awt.Color(203, 218, 64));
        jSeparator1.setForeground(new java.awt.Color(164, 238, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 470));

        bcghomelabel.setBackground(new java.awt.Color(82, 3, 68));
        bcghomelabel.setForeground(new java.awt.Color(254, 254, 254));
        bcghomelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/rsz_nyx.jpg"))); // NOI18N
        bcghomelabel.setText("ASDASADASDASDASDSA");
        bcghomelabel.setOpaque(true);
        getContentPane().add(bcghomelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        this.dispose();
        try {
            new Home().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Nyx.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked

        no.setContent(cont);
        curUser.addTalk(no);
        
        FileOutputStream fout = null;
        File ff = new File("users/"+curUser.getUsername()+".ser");
        ff.delete();
        try {
            fout = new FileOutputStream("users/"+curUser.getUsername()+".ser");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectOutputStream oos = null;
        try {
            oos = new ObjectOutputStream(fout);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            oos.writeObject(curUser);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        try {
            new Home().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_SaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nyx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nyx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nyx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nyx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Nyx().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(Nyx.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea NyxPane;
    private javax.swing.JButton Save;
    private javax.swing.JLabel bcghomelabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField saying;
    // End of variables declaration//GEN-END:variables
}
