/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projket;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author abdurrezzak
 */
public class SignUp extends javax.swing.JFrame {

    
    
    public SignUp() throws FileNotFoundException {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        overlay.setBackground(new Color(82,3,68,170));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        goToLogin = new javax.swing.JLabel();
        chosenUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        chosenPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        signUpBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        okTerms = new javax.swing.JRadioButton();
        info = new javax.swing.JLabel();
        termsLink = new javax.swing.JLabel();
        okTerms2 = new javax.swing.JLabel();
        overlay = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 670));
        setSize(new java.awt.Dimension(1280, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(82, 3, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goToLogin.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        goToLogin.setForeground(new java.awt.Color(77, 93, 223));
        goToLogin.setText("Go to Login!");
        goToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToLoginMouseClicked(evt);
            }
        });
        jPanel2.add(goToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        chosenUsername.setBackground(new java.awt.Color(82, 3, 68));
        chosenUsername.setForeground(new java.awt.Color(254, 254, 254));
        chosenUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chosenUsername.setCaretColor(new java.awt.Color(254, 254, 254));
        chosenUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chosenUsernameFocusGained(evt);
            }
        });
        chosenUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chosenUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(chosenUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 370, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 370, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 370, 20));

        chosenPassword.setBackground(new java.awt.Color(82, 3, 68));
        chosenPassword.setForeground(new java.awt.Color(254, 254, 254));
        chosenPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chosenPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chosenPasswordFocusGained(evt);
            }
        });
        jPanel2.add(chosenPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 370, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 205, 248));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        signUpBut.setBackground(new java.awt.Color(251, 124, 170));
        signUpBut.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        signUpBut.setText("Sign Up!");
        signUpBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        signUpBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButMouseClicked(evt);
            }
        });
        signUpBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButActionPerformed(evt);
            }
        });
        jPanel2.add(signUpBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 370, 40));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 205, 248));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(110, 6, 91));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 20, -1));

        jLabel9.setFont(new java.awt.Font("Symbola", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 8, 147));
        jLabel9.setText("Welcome to world's biggest introvert society! ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 520, 50));

        okTerms.setForeground(new java.awt.Color(246, 8, 147));
        okTerms.setText("I read the");
        okTerms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okTermsActionPerformed(evt);
            }
        });
        jPanel2.add(okTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        info.setForeground(new java.awt.Color(246, 8, 147));
        info.setText("How safe will my data be?");
        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 288, 360, 30));

        termsLink.setForeground(new java.awt.Color(254, 254, 254));
        termsLink.setText("terms");
        jPanel2.add(termsLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 40));

        okTerms2.setForeground(new java.awt.Color(246, 8, 147));
        okTerms2.setText("of usage and accept them.");
        jPanel2.add(okTerms2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 220, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 760, 670));

        overlay.setBackground(new java.awt.Color(1, 1, 1));
        overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/logo.png"))); // NOI18N
        overlay.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 470, 200));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(253, 243, 252));
        jLabel7.setText("Brand new heaven for introverts!");
        overlay.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, 20));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 210, 241));
        jLabel1.setText("“People empty me. I have to get away to refill.” ~ C. Bukowski");
        overlay.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 420, 80));

        getContentPane().add(overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 670));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/bcg.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chosenUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chosenUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chosenUsernameActionPerformed

    private void signUpButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButActionPerformed

    private void chosenUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chosenUsernameFocusGained
        // TODO add your handling code here:
        jLabel2.setForeground(new Color(251,11,247));
        jLabel3.setForeground(new Color(253,205,248));
    }//GEN-LAST:event_chosenUsernameFocusGained

    private void chosenPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chosenPasswordFocusGained
        // TODO add your handling code here:
        jLabel2.setForeground(new Color(253,205,248));
        jLabel3.setForeground(new Color(251,11,247));
    }//GEN-LAST:event_chosenPasswordFocusGained

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void okTermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okTermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okTermsActionPerformed

    private void goToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLoginMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_goToLoginMouseClicked

    
    private void signUpButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButMouseClicked
        
        if(okTerms.isSelected())
        {
            if(new String(chosenPassword.getPassword()).length() > 6)
            {
                String usr = chosenUsername.getText();
                File f = new File( "users/"+usr+".ser");
                if(f.exists() && !f.isDirectory()) { 
                    
                    JOptionPane.showMessageDialog(new JFrame(), "The username is not available, it is already in use.");
                
                }else
                {
                    FileOutputStream fout = null;
                    try {
                        User newUser = new User(chosenUsername.getText(), new String(chosenPassword.getPassword()));
                        fout = new FileOutputStream("users/"+usr+".ser");
                        ObjectOutputStream oos = new ObjectOutputStream(fout);
                        oos.writeObject(newUser);
                        JOptionPane.showMessageDialog(new JFrame(), "Your account has been created successfully.");
                        
                        
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            fout.close();
                        } catch (IOException ex) {
                            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(new JFrame(), "Your password must be longer than 6 characters.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(new JFrame(), "Please read and accept the terms of use.");
        }
        /*for(int i=0;i<allUsers.size();i++)
            JOptionPane.showMessageDialog(new JFrame(), allUsers.get(i).getUsername());*/
         
        
    }//GEN-LAST:event_signUpButMouseClicked

    
    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new SignUp().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField chosenPassword;
    private javax.swing.JTextField chosenUsername;
    private javax.swing.JLabel goToLogin;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton okTerms;
    private javax.swing.JLabel okTerms2;
    private javax.swing.JPanel overlay;
    private javax.swing.JButton signUpBut;
    private javax.swing.JLabel termsLink;
    // End of variables declaration//GEN-END:variables
}
