/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projket;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author abdurrezzak
 */
public class YourDays extends javax.swing.JFrame {

    User curUser = new User();
    String curusername="";
    ArrayList<Day> usersdays = new ArrayList<>();
    
    public YourDays() throws FileNotFoundException, IOException, ClassNotFoundException {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        jPanel1.setBackground(new Color(82,3,68,0));
        aDayTitle.setBackground(new Color(0,0,0,0));
        /*
            this part figures out who logged in
        */
        String line = null; 
        FileReader fileReader = new FileReader("sessions/usernames.txt");
        try (BufferedReader bufferedReader = new BufferedReader(fileReader)) {
            while((line = bufferedReader.readLine()) != null) {
                curusername = line;
            }
        } 
        
        
        FileInputStream fis = new FileInputStream("users/"+curusername+".ser");
        ObjectInputStream ois = new ObjectInputStream(fis);
        curUser = (User) ois.readObject();
        
        
        //getting current info
        propicLabel.setIcon(new ImageIcon(new ImageIcon(curUser.getProfilePicture()).getImage().getScaledInstance(200, 150, Image.SCALE_SMOOTH)));
        usernameLabel.setText("Welcome "+curUser.getUsername() + "!");
        
        creatingNewDay.setVisible(false);
        newDayTitle.setBackground(new Color(0,0,0,0));
        newDayContent.setBackground(new Color(0,0,0,0));
        
        usersdays = curUser.getDays();
        
        DefaultListModel dm = new DefaultListModel();
        
        for(int i=0;i<curUser.getDays().size();i++)
        {
            dm.addElement(curUser.getDays().get(i).getTitle());
            
        }
        
        oldDaysList.setModel(dm);
        
        aDayFrame.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aDayFrame = new javax.swing.JPanel();
        aDayTitle = new javax.swing.JTextField();
        aDayDeleteBut = new javax.swing.JButton();
        asdas = new javax.swing.JScrollPane();
        aDayContent = new javax.swing.JTextArea();
        aDaybcg = new javax.swing.JLabel();
        creatingNewDay = new javax.swing.JPanel();
        sep = new javax.swing.JSeparator();
        sep1 = new javax.swing.JSeparator();
        createdDay = new javax.swing.JButton();
        newDayTitle = new javax.swing.JTextField();
        Bday = new javax.swing.JRadioButton();
        Happy = new javax.swing.JRadioButton();
        Sad = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        newDayContent = new javax.swing.JTextArea();
        crNewDayBcg = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        oldDaysList = new javax.swing.JList<>();
        addNewDay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nyxBut = new javax.swing.JButton();
        newEntryBut = new javax.swing.JButton();
        yourDaysBut = new javax.swing.JButton();
        propicLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        notesBut = new javax.swing.JButton();
        oldEntriesBut = new javax.swing.JButton();
        albumsBut = new javax.swing.JButton();
        oldTalksBut = new javax.swing.JButton();
        exitBut = new javax.swing.JLabel();
        settingsBut = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bcghomelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 670));
        setMinimumSize(new java.awt.Dimension(1280, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aDayFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aDayFrameMouseClicked(evt);
            }
        });
        aDayFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aDayTitle.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        aDayTitle.setForeground(new java.awt.Color(217, 81, 210));
        aDayTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aDayFrame.add(aDayTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 430, 60));

        aDayDeleteBut.setText("Delete");
        aDayDeleteBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aDayDeleteButMouseClicked(evt);
            }
        });
        aDayFrame.add(aDayDeleteBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 110, 40));

        aDayContent.setColumns(20);
        aDayContent.setForeground(new java.awt.Color(60, 22, 234));
        aDayContent.setLineWrap(true);
        aDayContent.setRows(15);
        aDayContent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        asdas.setViewportView(aDayContent);

        aDayFrame.add(asdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 560, 320));
        aDayFrame.add(aDaybcg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -5, 730, 550));

        getContentPane().add(aDayFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 720, 540));

        creatingNewDay.setBackground(new java.awt.Color(1, 46, 61));
        creatingNewDay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sep.setBackground(new java.awt.Color(153, 54, 203));
        sep.setForeground(new java.awt.Color(216, 67, 220));
        creatingNewDay.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 630, 20));

        sep1.setBackground(new java.awt.Color(153, 54, 203));
        sep1.setForeground(new java.awt.Color(216, 67, 220));
        creatingNewDay.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 630, 20));

        createdDay.setText("Add");
        createdDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createdDayMouseClicked(evt);
            }
        });
        creatingNewDay.add(createdDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 100, 40));

        newDayTitle.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        newDayTitle.setForeground(new java.awt.Color(223, 142, 206));
        newDayTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        creatingNewDay.add(newDayTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 570, 50));

        Bday.setForeground(new java.awt.Color(223, 142, 206));
        Bday.setText("Birthday");
        creatingNewDay.add(Bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 170, 50));

        Happy.setForeground(new java.awt.Color(223, 142, 206));
        Happy.setText("Happy");
        creatingNewDay.add(Happy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 170, 50));

        Sad.setForeground(new java.awt.Color(223, 142, 206));
        Sad.setText("Sad");
        creatingNewDay.add(Sad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 170, 50));

        newDayContent.setColumns(20);
        newDayContent.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        newDayContent.setForeground(new java.awt.Color(74, 42, 89));
        newDayContent.setLineWrap(true);
        newDayContent.setRows(10);
        jScrollPane1.setViewportView(newDayContent);

        creatingNewDay.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 630, 230));
        creatingNewDay.add(crNewDayBcg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        getContentPane().add(creatingNewDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 710, 480));

        oldDaysList.setBackground(new java.awt.Color(36, 27, 52));
        oldDaysList.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        oldDaysList.setForeground(new java.awt.Color(248, 234, 249));
        oldDaysList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        oldDaysList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                oldDaysListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(oldDaysList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 640, 460));

        addNewDay.setText("New Day!");
        addNewDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewDayMouseClicked(evt);
            }
        });
        getContentPane().add(addNewDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 130, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/rsz_2logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 240, 100));

        jLabel1.setFont(new java.awt.Font("Symbola", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 210));
        jLabel1.setText("Your special days");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 450, 50));

        jPanel1.setBackground(new java.awt.Color(82, 3, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nyxBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        nyxBut.setForeground(new java.awt.Color(1, 1, 1));
        nyxBut.setText("TALK TO NYX");
        nyxBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nyxBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nyxBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        nyxBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nyxButMouseClicked(evt);
            }
        });
        nyxBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyxButActionPerformed(evt);
            }
        });
        jPanel1.add(nyxBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 260, 40));

        newEntryBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        newEntryBut.setForeground(new java.awt.Color(1, 1, 1));
        newEntryBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/addentry.png"))); // NOI18N
        newEntryBut.setText("New Entry");
        newEntryBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        newEntryBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newEntryBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newEntryBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        newEntryBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newEntryButMouseClicked(evt);
            }
        });
        newEntryBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntryButActionPerformed(evt);
            }
        });
        jPanel1.add(newEntryBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 40));

        yourDaysBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        yourDaysBut.setForeground(new java.awt.Color(1, 1, 1));
        yourDaysBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/yourdays.png"))); // NOI18N
        yourDaysBut.setText("Your Days");
        yourDaysBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        yourDaysBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        yourDaysBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        yourDaysBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        yourDaysBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yourDaysButMouseClicked(evt);
            }
        });
        yourDaysBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourDaysButActionPerformed(evt);
            }
        });
        jPanel1.add(yourDaysBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 40));

        propicLabel.setBackground(new java.awt.Color(221, 128, 35));
        propicLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        propicLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propicLabelMouseClicked(evt);
            }
        });
        jPanel1.add(propicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 150));

        usernameLabel.setFont(new java.awt.Font("Symbola", 2, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 40));

        notesBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        notesBut.setForeground(new java.awt.Color(1, 1, 1));
        notesBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/notes.png"))); // NOI18N
        notesBut.setText("Notes");
        notesBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notesBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        notesBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        notesBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        notesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesButMouseClicked(evt);
            }
        });
        notesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesButActionPerformed(evt);
            }
        });
        jPanel1.add(notesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 40));

        oldEntriesBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        oldEntriesBut.setForeground(new java.awt.Color(1, 1, 1));
        oldEntriesBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/oldentries.png"))); // NOI18N
        oldEntriesBut.setText("Old Entries");
        oldEntriesBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        oldEntriesBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        oldEntriesBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        oldEntriesBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        oldEntriesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldEntriesButMouseClicked(evt);
            }
        });
        oldEntriesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldEntriesButActionPerformed(evt);
            }
        });
        jPanel1.add(oldEntriesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 40));

        albumsBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        albumsBut.setForeground(new java.awt.Color(1, 1, 1));
        albumsBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/albums.png"))); // NOI18N
        albumsBut.setText("Albums");
        albumsBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        albumsBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        albumsBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        albumsBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        albumsBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumsButMouseClicked(evt);
            }
        });
        albumsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumsButActionPerformed(evt);
            }
        });
        jPanel1.add(albumsBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 120, 40));

        oldTalksBut.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        oldTalksBut.setForeground(new java.awt.Color(1, 1, 1));
        oldTalksBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/oldtalks.png"))); // NOI18N
        oldTalksBut.setText("Old Talks");
        oldTalksBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        oldTalksBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        oldTalksBut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        oldTalksBut.setMargin(new java.awt.Insets(0, 100, 0, 0));
        oldTalksBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldTalksButMouseClicked(evt);
            }
        });
        oldTalksBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldTalksButActionPerformed(evt);
            }
        });
        jPanel1.add(oldTalksBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 40));

        exitBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/exitt.png"))); // NOI18N
        exitBut.setText("jLabel3");
        exitBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButMouseClicked(evt);
            }
        });
        jPanel1.add(exitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 50, 50));

        settingsBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/settings.png"))); // NOI18N
        settingsBut.setText("jLabel3");
        settingsBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButMouseClicked(evt);
            }
        });
        jPanel1.add(settingsBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 290, 520));

        jSeparator1.setBackground(new java.awt.Color(203, 218, 64));
        jSeparator1.setForeground(new java.awt.Color(164, 238, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 470));

        bcghomelabel.setBackground(new java.awt.Color(82, 3, 68));
        bcghomelabel.setForeground(new java.awt.Color(254, 254, 254));
        bcghomelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projket/bcghome.jpg"))); // NOI18N
        bcghomelabel.setText("ASDASADASDASDASDSA");
        bcghomelabel.setOpaque(true);
        getContentPane().add(bcghomelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nyxButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyxButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyxButActionPerformed

    private void newEntryButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntryButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEntryButActionPerformed

    private void yourDaysButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourDaysButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yourDaysButActionPerformed

    private void propicLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propicLabelMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        
        propicLabel.setIcon(new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(200, 150, Image.SCALE_SMOOTH)));
        //ImageIcon icon=new ImageIcon(filename);
        //jLabel3.setIcon(icon);
        
    }//GEN-LAST:event_propicLabelMouseClicked

    private void notesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notesButActionPerformed

    private void oldEntriesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldEntriesButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldEntriesButActionPerformed

    private void albumsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumsButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumsButActionPerformed

    private void oldTalksButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldTalksButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldTalksButActionPerformed

    private void exitButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_exitButMouseClicked

    private void settingsButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButMouseClicked
        this.setVisible(false);
        try {
            new Settings().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_settingsButMouseClicked

    private void newEntryButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEntryButMouseClicked
        
        this.setVisible(false);
        try {
            new NewEntry().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newEntryButMouseClicked

    private void notesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesButMouseClicked
        this.setVisible(false);
        try {
            new Notes().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_notesButMouseClicked

    private void yourDaysButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yourDaysButMouseClicked
        this.setVisible(false);
        try {
            new YourDays().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yourDaysButMouseClicked

    private void oldEntriesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldEntriesButMouseClicked
        this.setVisible(false);
        try {
            new OldEntries().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_oldEntriesButMouseClicked

    private void oldTalksButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldTalksButMouseClicked
        this.setVisible(false);
        try {
            new OldTalks().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_oldTalksButMouseClicked

    private void albumsButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumsButMouseClicked
        this.setVisible(false);
        try {
            new Albums().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_albumsButMouseClicked

    private void nyxButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nyxButMouseClicked
        this.setVisible(false);
        try {
            new Nyx().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nyxButMouseClicked

    private void addNewDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewDayMouseClicked
        
        creatingNewDay.setVisible(true);
    }//GEN-LAST:event_addNewDayMouseClicked

    private void createdDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createdDayMouseClicked
        
        Day nd = new Day();
        
        if(!newDayTitle.getText().equals(""))
            nd.setTitle(newDayTitle.getText());
        nd.setContent(newDayContent.getText());
        
        if(Happy.isEnabled())
            nd.setType("Happy");
        else if(Sad.isEnabled())
            nd.setType("Sad");
        else if(Bday.isEnabled())
            nd.setType("Birthday");
        
        
        curUser.addDay(nd);
        
        
        FileOutputStream fout = null;
        File ff = new File("users/"+curUser.getUsername()+".ser");
        ff.delete();
        
        try {
            fout = new FileOutputStream("users/"+curUser.getUsername()+".ser");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectOutputStream oos = null;
        try {
            oos = new ObjectOutputStream(fout);
        } catch (IOException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            oos.writeObject(curUser);
        } catch (IOException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        creatingNewDay.setVisible(false);
        this.dispose();
        try {
            new YourDays().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createdDayMouseClicked

    private void oldDaysListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_oldDaysListValueChanged

        
        try{
            int i = oldDaysList.getSelectedIndex();
            
            
            //JOptionPane.showMessageDialog(new JFrame(), "You seem to have forgotten your password, please try again.");

            Day n = new Day();
            n.setTitle(oldDaysList.getSelectedValue());
            n = curUser.getSpecificDay(n);
            aDayTitle.setText(n.getTitle());
            aDayContent.setText(n.getContent());
            aDayFrame.setVisible(true);
            oldDaysList.setVisible(false);
            addNewDay.setVisible(false);
            
            if(n.getType().equals("Happy"))
            {
                aDaybcg.setIcon(new ImageIcon(new ImageIcon("/home/abdurrezzak/NetBeansProjects/Projket/src/projket/happyDaybcg.jpg")
                        .getImage().getScaledInstance(730, 550, Image.SCALE_SMOOTH)));
                
            }
            else if(n.getType().equals("Sad"))
            {
             
                aDaybcg.setIcon(new ImageIcon(new ImageIcon("/home/abdurrezzak/NetBeansProjects/Projket/src/projket/sadDaybcg.jpg")
                        .getImage().getScaledInstance(730, 550, Image.SCALE_SMOOTH)));
               
            }
            else if(n.getType().equals("Birthday"))
            {
                aDaybcg.setIcon(new ImageIcon(new ImageIcon("/home/abdurrezzak/NetBeansProjects/Projket/src/projket/bDaybcg.jpg")
                        .getImage().getScaledInstance(730, 550, Image.SCALE_SMOOTH)));
            }
            
            aDayContent.setBackground(new Color(82,3,68,10));
            
        }catch(NullPointerException e)
        {
            
        }

    }//GEN-LAST:event_oldDaysListValueChanged

    private void aDayFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aDayFrameMouseClicked

        aDayFrame.setVisible(false);
        this.dispose();
        try {
            new YourDays().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aDayFrameMouseClicked

    private void aDayDeleteButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aDayDeleteButMouseClicked
   
        Day d = new Day();
        d.setTitle(aDayTitle.getText());
        
        curUser.deleteDay(d);
        
        FileOutputStream fout = null;
        File ff = new File("users/"+curUser.getUsername()+".ser");
        ff.delete();
        
        try {
            fout = new FileOutputStream("users/"+curUser.getUsername()+".ser");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectOutputStream oos = null;
        try {
            oos = new ObjectOutputStream(fout);
        } catch (IOException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            oos.writeObject(curUser);
        } catch (IOException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
        try {
            new YourDays().setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        

    }//GEN-LAST:event_aDayDeleteButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YourDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YourDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YourDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YourDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new YourDays().setVisible(true);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(YourDays.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bday;
    private javax.swing.JRadioButton Happy;
    private javax.swing.JRadioButton Sad;
    private javax.swing.JTextArea aDayContent;
    private javax.swing.JButton aDayDeleteBut;
    private javax.swing.JPanel aDayFrame;
    private javax.swing.JTextField aDayTitle;
    private javax.swing.JLabel aDaybcg;
    private javax.swing.JButton addNewDay;
    private javax.swing.JButton albumsBut;
    private javax.swing.JScrollPane asdas;
    private javax.swing.JLabel bcghomelabel;
    private javax.swing.JLabel crNewDayBcg;
    private javax.swing.JButton createdDay;
    private javax.swing.JPanel creatingNewDay;
    private javax.swing.JLabel exitBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea newDayContent;
    private javax.swing.JTextField newDayTitle;
    private javax.swing.JButton newEntryBut;
    private javax.swing.JButton notesBut;
    private javax.swing.JButton nyxBut;
    private javax.swing.JList<String> oldDaysList;
    private javax.swing.JButton oldEntriesBut;
    private javax.swing.JButton oldTalksBut;
    private javax.swing.JLabel propicLabel;
    private javax.swing.JSeparator sep;
    private javax.swing.JSeparator sep1;
    private javax.swing.JLabel settingsBut;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton yourDaysBut;
    // End of variables declaration//GEN-END:variables

    
}
